version: "2.4"
services:
  db-sqlm:
    image: postgres:latest
    container_name: sqlm-db-int
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sqlm-int
      - POSTGRES_USER=sqlm-int-user
      - POSTGRES_PASSWORD=welcome

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 60s
