-- +migrate Up
CREATE EXTENSION IF NOT EXISTS citext;

-- +migrate Up
create table user_account (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	, name varchar(255)
	, email citext unique not null
	, vendor_id varchar(255)
	, password_hash bytea not null
	, activated bool not null
	, role varchar(20) not null
	, created_at timestamp
	, version bigint not null default 1
	);

-- +migrate Down
alter table if exists users_teams drop constraint if exists fk_user;
alter table if exists token drop constraint if exists fk_user;
drop table if exists user_account;

-- +migrate Up
create table team (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	, name text unique not null
	, type varchar(255)
	, team_meta_id int
	, updated_at timestamp
	, created_at timestamp
	, version bigint not null default 1
	);

-- +migrate Down
alter table if exists users_teams drop constraint if exists fk_team;
alter table if exists team_meta drop constraint if exists fk_team_meta;
drop table team;

-- +migrate Up
create table team_meta(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	, git_url varchar(500)
	, server_url varchar(500)
	, updated_at timestamp
	, created_at timestamp
	, version bigint not null default 1
	);

-- +migrate Down
drop table team_meta;

-- +migrate Up
create table users_teams (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	, user_account_id int
	, team_id int
	, is_admin int
	, created_at timestamp
	, version bigint not null default 1
	);

-- +migrate Down
drop table if exists users_teams;

-- +migrate Up
create table token (
	hash bytea primary key
	, user_account_id bigint 
	, expiry timestamp with time zone not null
	, scope text not null
);

-- +migrate Down
drop table if exists token;

-- +migrate Up
alter table users_teams add constraint fk_user foreign key(user_account_id) references user_account(id) on delete cascade;

-- +migrate Up
alter table users_teams add constraint fk_team foreign key(team_id) references team(id) on delete cascade;

-- +migrate Up
alter table team add constraint fk_team_meta foreign key(team_meta_id) references team_meta(id);

-- +migrate Up
alter table token add constraint fk_user foreign key(user_account_id) references user_account(id) on delete cascade;